stages:
  prepare:
    cmd: python src/prepare.py data/raw/train.csv
    params:
      - prepare.seed
      - prepare.split
    deps:
      - data/raw/train.csv
      - src/prepare.py
    outs:
      - data/processed/test.csv
      - data/processed/train.csv
