stages:
  prepare:
    cmd: prepare.split -d src/prepare.py -d data/raw/train.csv -o data/processed/train.csv
      -o data/processed/test.csv python src/prepare.py data/raw/train.csv
    params:
    - prepare.seed
